### ISSUE TITLE
Chapter_1/bayes.py

### ISSUE THREAD

**Issue by omniqa** [rlvaugh/Real_World_Python#5]
Hi, getting this error:

```
Traceback (most recent call last):
  File "bayes.py", line 217, in <module>
    main()
  File "bayes.py", line 210, in main
    cv.circle(app.img, (sailor_x[0], sailor_y[0]), 3, (255, 0, 0), -1)
TypeError: 'int' object is not subscriptable
```

sailor_x, sailor_y are int why do you treat them as arrays?

`    cv.circle(app.img, (sailor_x, sailor_y), 3, (255, 0, 0), -1)
`
this is working fine....

**Comment by rlvaugh** [comment]
Several users have had problems with drawing the circle even though the original version of the program ran without problems for both myself and my technical reviewers using different platforms. We haven't been able to reproduce the errors, but have been modifying the program so that it will hopefully work for everyone (if possible). The line that draws the circle did not get updated correctly on GitHub during the last round of corrections. As you point out, it should be:

cv.circle(app.img, (sailor_x, sailor_y), 3, (255, 0, 0), -1)

Thank you for pointing this out.

**Comment by rdmacko** [comment]
suggestion: Also, make the circle larger than 3 so it is more easily seen.

**Comment by jazad136** [comment]
Hi, I found that I was also getting this error. In my print of the book it was written this way:
cv.circle(app.img, (sailor_x, sailor_y), 3, (255, 0, 0), -1)
(ISBN 978-1-7815-0062-4)
but this gave me errors. 

I found that it was because the `sailor_final_location()` function was originally two 1-dimensional arrays. 
`return x, y`

To fix, I added int casts to both elements of the returned tuple in the `sailor_final_location()` function. 
`return int(x), int(y)`

The end result: cv.circle no longer complains because it is passed int values instead of arrays.

**Comment by jazad136** [comment]
Hi, I found that I was also getting this error. In my print of the book it was written this way:
`cv.circle(app.img, (sailor_x, sailor_y), 3, (255, 0, 0), -1)`
(ISBN 978-1-7815-0062-4)
but this gave me errors.

I found that it was because the sailor_final_location() function was originally returning two 1-dimensional arrays.
`return x, y`

To fix, I added int casts to both elements of the returned tuple in the sailor_final_location() function.
`return int(x), int(y)`

The end result: cv.circle no longer complains because it is passed int values instead of arrays.

**Comment by rlvaugh** [comment]
This should also work, changing the code above as follows:

**Page 15: Listing 1-4, lines 4 & 5 (90 & 91 in code) that read:**
self.sailor_actual[0] = np.random.choice(self.sa1.shape[1], 1)
self.sailor_actual[1] = np.random.choice(self.sa1.shape[0], 1)
**Should read as:**
self.sailor_actual[0] = np.random.choice(self.sa1.shape[1])
self.sailor_actual[1] = np.random.choice(self.sa1.shape[0])

**Comment by cbdp** [comment]
I originally fixed this the same way @jazad136 did, but I put the int()s in cv.circle. Though it worked, it baffled me for a while as to HOW it worked and WHY it was needed. I much prefer @rlvaugh Changing self.sailor_actual[0] = np.random.choice(self.sa1.shape[1], 1) to self.sailor_actual[0] = np.random.choice(self.sa1.shape[1]), since it's much more understandable.
